import type { ReportExport, ReportExportType } from './reportsApi';

const metadata = [
  ['reportPeriodStart', 'Report period start'],
  ['reportPeriodEnd', 'Report period end'],
  ['snapshotAt', 'Snapshot at'],
  ['generatedAt', 'Generated at'],
  ['generatedBy', 'Generated by'],
  ['peopleScope', 'People scope'],
  ['reportingGroupFilter', 'Reporting group filter'],
  ['areaFilter', 'Area/Squad filter'],
] as const;

const schemas: Record<
  ReportExportType,
  readonly (readonly [string, string])[]
> = {
  ticket_summary: [
    ['ticketId', 'Ticket ID'],
    ['title', 'Title'],
    ['area', 'Area/Squad'],
    ['labels', 'Labels'],
    ['statusAtPeriodEnd', 'Status at period end'],
    ['primaryAssigneeAtPeriodEnd', 'Primary assignee at period end'],
    ['contributorsDuringPeriod', 'Contributors during period'],
    ['plannedStartDate', 'Planned start date'],
    ['dueDate', 'Due date'],
    ['dueState', 'Due state'],
    ['firstWorkDate', 'First actual work date'],
    ['lastWorkDate', 'Last actual work date'],
    ['activeWorkDays', 'Active work days'],
    ['workEntries', 'Work entries'],
    ['completedTransitions', 'Completed transitions'],
    ['reopenTransitions', 'Reopen transitions'],
    ['blockedAtPeriodEnd', 'Blocked at period end'],
    ['blockedCalendarDays', 'Blocked calendar days'],
    ['completedSubtasks', 'Completed subtasks'],
    ['totalSubtasks', 'Total subtasks'],
    ['archivedAtPeriodEnd', 'Archived at period end'],
  ],
  ticket_activity: [
    ['workEntryId', 'Work entry ID'],
    ['workBatchId', 'Work batch ID'],
    ['ticketId', 'Ticket ID'],
    ['ticketTitle', 'Ticket title'],
    ['area', 'Area/Squad'],
    ['workDate', 'Work date'],
    ['workedBy', 'Worked by'],
    ['reportingLead', 'Reporting Lead'],
    ['reportingManager', 'Reporting Manager'],
    ['loggedBy', 'Submitted by'],
    ['primaryAssignee', 'Primary assignee on work date'],
    ['relationship', 'Relationship'],
    ['ticketStatus', 'Ticket status on work date'],
    ['workType', 'Work type'],
    ['description', 'Description'],
    ['loggedAt', 'Logged at'],
    ['lastEditedAt', 'Last edited at'],
  ],
  designer_summary: [
    ['designer', 'Designer'],
    ['workEmail', 'Work email'],
    ['position', 'Position'],
    ['adminPrivilege', 'Admin privilege'],
    ['reportingLeadAtPeriodEnd', 'Reporting Lead at period end'],
    ['reportingManagerAtPeriodEnd', 'Reporting Manager at period end'],
    ['reportingLeadsDuringPeriod', 'Reporting Leads during period'],
    ['reportingManagersDuringPeriod', 'Reporting Managers during period'],
    ['activeOwnedTickets', 'Active owned tickets'],
    ['ticketsWorkedOn', 'Tickets worked on'],
    ['ticketActiveDays', 'Ticket active days'],
    ['ticketDays', 'Ticket-days'],
    ['completedAsPrimary', 'Completed as primary'],
    ['contributedTickets', 'Contributed tickets'],
    ['primaryTicketDays', 'Primary ticket-days'],
    ['contributorTicketDays', 'Contributor ticket-days'],
    ['blockedOwnedTickets', 'Blocked owned tickets'],
    ['overdueOwnedTickets', 'Overdue owned tickets'],
    ['ownedTicketsWithoutWork', 'Owned tickets without period work'],
    ['lastRecordedWorkDate', 'Last recorded work date'],
    ['plannedUntil', 'Planned until'],
    [
      'activeOwnedTicketsWithoutDueDates',
      'Active owned tickets without due dates',
    ],
    ['visualActivityDays', 'Visual activity-days'],
    ['overallActiveCalendarDays', 'Overall active calendar days'],
  ],
  designer_ticket: [
    ['designer', 'Designer'],
    ['reportingLeadDuringActivity', 'Reporting Lead during activity'],
    ['reportingManagerDuringActivity', 'Reporting Manager during activity'],
    ['ticketId', 'Ticket ID'],
    ['ticketTitle', 'Ticket title'],
    ['area', 'Area/Squad'],
    ['relationship', 'Relationship'],
    ['firstActivityDate', 'First activity date'],
    ['lastActivityDate', 'Last activity date'],
    ['ticketDays', 'Ticket-days'],
    ['workTypes', 'Work types'],
    ['completedAsPrimaryTransitions', 'Completed as primary transitions'],
    ['statusAtPeriodEnd', 'Status at period end'],
    ['primaryAssigneeAtPeriodEnd', 'Primary assignee at period end'],
    ['dueDate', 'Due date'],
    ['lastWorkedOnAtPeriodEnd', 'Last worked on at period end'],
  ],
  visual_work: [
    ['visualWorkEntryId', 'Visual work entry ID'],
    ['workBatchId', 'Work batch ID'],
    ['designer', 'Designer'],
    ['reportingLead', 'Reporting Lead'],
    ['reportingManager', 'Reporting Manager'],
    ['workDate', 'Work date'],
    ['visualWorkType', 'Visual-work type'],
    ['area', 'Area/Squad'],
    ['description', 'Description'],
    ['loggedBy', 'Submitted by'],
    ['loggedAt', 'Logged at'],
    ['lastEditedAt', 'Last edited at'],
  ],
};

const text = (value: unknown): string =>
  value == null
    ? ''
    : Array.isArray(value)
      ? value.map(text).join(' | ')
      : typeof value === 'object'
        ? JSON.stringify(value)
        : typeof value === 'string' ||
            typeof value === 'number' ||
            typeof value === 'boolean' ||
            typeof value === 'bigint'
          ? String(value)
          : '';
const escape = (value: unknown) => `"${text(value).replaceAll('"', '""')}"`;

export function serializeReportCsv(payload: ReportExport): string {
  const type = payload.reportType as ReportExportType;
  const columns = [...metadata, ...schemas[type]];
  if (!schemas[type]) throw new Error('Unsupported report export type.');
  return [
    columns.map(([, label]) => escape(label)).join(','),
    ...payload.rows.map((row) =>
      columns
        .map(([key]) => escape(key in row ? row[key] : payload.metadata[key]))
        .join(','),
    ),
  ].join('\r\n');
}

export function downloadCsv(payload: ReportExport) {
  const csv = serializeReportCsv(payload);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  const startValue = text(payload.metadata.reportPeriodStart);
  const endValue = text(payload.metadata.reportPeriodEnd);
  const start = startValue.length ? startValue : 'start';
  const end = endValue.length ? endValue : 'end';
  anchor.href = url;
  anchor.download = `${payload.reportType}_${start}_${end}.csv`;
  anchor.click();
  URL.revokeObjectURL(url);
}
