const humanize = (value: string) =>
  value
    .replaceAll(/([A-Z])/g, ' $1')
    .replaceAll('_', ' ')
    .replace(/^./, (letter) => letter.toUpperCase());
const recordKey = (value: unknown, key: string) => {
  const candidate =
    typeof value === 'object' && value !== null
      ? (value as Record<string, unknown>)[key]
      : undefined;
  return typeof candidate === 'string' || typeof candidate === 'number'
    ? String(candidate)
    : '';
};
const valueText = (value: unknown): string => {
  if (value == null || value === '') return '—';
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  if (Array.isArray(value)) return value.map(valueText).join(' | ') || '—';
  if (typeof value === 'object') {
    const record = value as Record<string, unknown>;
    const preferred = [
      record.displayName,
      record.label,
      record.name,
      record.title,
    ].find(
      (candidate) =>
        typeof candidate === 'string' || typeof candidate === 'number',
    );
    return preferred === undefined ? JSON.stringify(record) : String(preferred);
  }
  return typeof value === 'string' ||
    typeof value === 'number' ||
    typeof value === 'boolean' ||
    typeof value === 'bigint'
    ? String(value)
    : '—';
};

export async function generateWorkItemPdf(payload: Record<string, unknown>) {
  const { jsPDF } = await import('jspdf');
  const item = (payload.workItem ?? {}) as Record<string, unknown>;
  const history = (payload.history ?? {}) as Record<string, unknown>;
  const comments = Array.isArray(payload.comments)
    ? [...(payload.comments as unknown[])].sort((a, b) =>
        recordKey(a, 'createdAt').localeCompare(recordKey(b, 'createdAt')),
      )
    : [];
  const displayId = valueText(item.displayId ?? 'work-item');
  const doc = new jsPDF({ unit: 'pt', format: 'a4', compress: false });
  const width = doc.internal.pageSize.getWidth();
  const height = doc.internal.pageSize.getHeight();
  const margin = 48;
  let y = 64;
  const lineHeight = 15;
  const ensure = (needed = 32) => {
    if (y + needed <= height - 54) return;
    doc.addPage();
    y = 64;
  };
  const heading = (text: string, level = 2) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(level === 1 ? 18 : 13);
    const lines = doc.splitTextToSize(text, width - margin * 2) as string[];
    const headingLineHeight = level === 1 ? 22 : 17;
    ensure(lines.length * headingLineHeight + 8);
    doc.text(lines, margin, y);
    y += lines.length * headingLineHeight + (level === 1 ? 10 : 5);
  };
  const paragraph = (label: string, value: unknown) => {
    const lines = doc.splitTextToSize(
      `${label}: ${valueText(value)}`,
      width - margin * 2,
    ) as string[];
    ensure(lines.length * lineHeight + 6);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(lines, margin, y);
    y += lines.length * lineHeight + 6;
  };

  heading(`${displayId} — ${valueText(item.title)}`, 1);
  paragraph('Generated at', payload.generatedAt);
  paragraph('Generated by', payload.generatedBy);
  heading('Current snapshot');
  const snapshotKeys = [
    'status',
    'area',
    'assignee',
    'contributors',
    'labels',
    'description',
    'plannedStartDate',
    'dueDate',
    'firstWorkedOn',
    'lastWorkedOn',
    'activeWorkDays',
    'completedAt',
    'isArchived',
  ];
  snapshotKeys.forEach((key) => paragraph(humanize(key), item[key]));
  if (typeof item.figmaUrl === 'string' && item.figmaUrl) {
    ensure(22);
    doc.setTextColor(0, 79, 140);
    doc.textWithLink('Open approved Figma URL', margin, y, {
      url: item.figmaUrl,
    });
    doc.setTextColor(0, 0, 0);
    y += 22;
  }
  for (const [title, key] of [
    ['Blockers', 'blockerHistory'],
    ['Subtasks', 'subtasks'],
  ] as const) {
    heading(title);
    const rows = Array.isArray(item[key]) ? item[key] : [];
    if (!rows.length) paragraph('Records', 'None');
    rows.forEach((row, index) =>
      paragraph(`${title.slice(0, -1)} ${index + 1}`, row),
    );
  }
  heading('Actual work dates');
  const workDates = Array.isArray(history.workDates)
    ? [...(history.workDates as unknown[])].sort((a, b) =>
        recordKey(a, 'date').localeCompare(recordKey(b, 'date')),
      )
    : [];
  if (!workDates.length) paragraph('Records', 'None');
  workDates.forEach((row, index) => paragraph(`Work date ${index + 1}`, row));
  heading('Status, assignment, and meaningful history');
  const events = Array.isArray(history.events)
    ? [...(history.events as unknown[])].sort((a, b) =>
        recordKey(a, 'occurredAt').localeCompare(recordKey(b, 'occurredAt')),
      )
    : [];
  if (!events.length) paragraph('Records', 'None');
  events.forEach((row, index) => paragraph(`History event ${index + 1}`, row));
  if (payload.includeComments) {
    heading('Comments');
    if (!comments.length) paragraph('Records', 'None');
    comments.forEach((row, index) => paragraph(`Comment ${index + 1}`, row));
  }

  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(90, 90, 90);
    doc.text(`${displayId} · Work Item export`, margin, 28);
    doc.text(`Page ${page} of ${pages}`, width - margin, height - 24, {
      align: 'right',
    });
  }
  return {
    bytes: new Uint8Array(doc.output('arraybuffer')),
    filename: `work-item_${displayId}_${valueText(payload.generatedAt ?? '').slice(0, 10) || 'generated'}.pdf`,
  };
}

export async function downloadWorkItemPdf(payload: Record<string, unknown>) {
  const output = await generateWorkItemPdf(payload);
  const url = URL.createObjectURL(
    new Blob([output.bytes], { type: 'application/pdf' }),
  );
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = output.filename;
  anchor.click();
  URL.revokeObjectURL(url);
}
